apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-images
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-images
  template:
    metadata:
      labels:
        app: nginx-images
    spec:
      containers:
        - name: micro-serve
          image: tejasvini1998/nginx-images:v1.1.0
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-images
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: nginx-images
